### ISSUE TITLE
unknown field 'joint'

### ISSUE THREAD

**Issue by WillDudley** [iory/mjcf2urdf#2]
file `model.xml`:
```

<mujoco model="model">
    <compiler inertiafromgeom="true"/>
    <option gravity="0 0 -9.81" integrator="RK4" timestep="0.001"/>
    <worldbody>
        <body name="ball" pos="0 0 .05">
            <joint armature="0" damping="0" limited="false" name="ball" pos="0 0 0" ref=".1" stiffness="0" type="free"/>
            <geom conaffinity="1" contype="1" name="ball" pos="0 0 0" rgba="0.8 0.8 0.8 1" size=".0258" mass=".01" type="sphere"/>
        </body>
    </worldbody>
</mujoco>
```

CLI input: `mjcf2urdf model.xml`

CL message: 
```
pybullet build time: Jun  2 2020 06:47:43
b3Warning[examples/SharedMemory/PhysicsServerCommandProcessor.cpp,3433]:
model.xml:6: unknown field 'joint'
```

Any idea what's going on?

**Comment by WillDudley** [comment]
This seems to be an issue with pyBullet and not mjcf2urdf, and I'm probably just missing something obvious. Apologies.

**Comment by ZuWang95** [comment]
I have a similar issue here, how did you solve this @WillDudley

**Comment by WillDudley** [comment]
> I have a similar issue here, how did you solve this @WillDudley 

Unfortunately it's been a while since working with mujoco or bullet, and I can't remember. It was likely an issue with pybullet's versioning. I remember I had to familiarise myself with the pybullet docs fairly in depth
